import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Web3Provider } from '@/providers/Web3Provider'
import './globals.scss'
import s from './layout.module.scss'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <Web3Provider>
          <main className={s.main}>{children}</main>
        </Web3Provider>
      </body>
    </html>
  )
}
